version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: no
    environment:
      POSTGRES_DB: trippal_db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: